[platformio]
default_envs = esp8266mod
src_dir = firmware/src

[env:esp8266mod]
platform = espressif8266
board = esp12e
framework = arduino
monitor_speed = 115200
upload_port = COM8
upload_speed = 115200
lib_deps =
  bodmer/TFT_eSPI@^2.5.43
  bblanchon/ArduinoJson@^7.4.2
  tzapu/WiFiManager@^2.0.17
build_flags =
  -D USER_SETUP_LOADED=1
  -D ST7789_DRIVER=1
  -D TFT_WIDTH=240
  -D TFT_HEIGHT=240
  -D TFT_MOSI=13
  -D TFT_SCLK=14
  -D TFT_CS=15
  -D TFT_DC=4
  -D TFT_RST=5
  -D LOAD_GLCD=1
  -D LOAD_FONT2=1
  -D LOAD_FONT4=1
  -D SPI_FREQUENCY=40000000



